import XCTest
@testable import GaeilgeTimeFormatter

final class GaeilgeTimeFormatterTests: XCTestCase {

    func createDate(hour: Int, minute: Int) -> Date {
        var components = DateComponents()
        components.hour = hour
        components.minute = minute
        components.year = 2024
        components.month = 1
        components.day = 1
        components.second = 0

        var calendar = Calendar.current
        calendar.timeZone = TimeZone(identifier: "UTC")!
        return calendar.date(from: components)!
    }

    func testAllJaneCorrections() {
        // --- 12:00 to 1:00 ---
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 1)), "Tá sé nóiméad amháin tar éis a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 11)), "Tá sé aon nóiméad déag tar éis a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 12)), "Tá sé dhá nóiméad déag tar éis a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 13)), "Tá sé trí nóiméad déag tar éis a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 14)), "Tá sé ceithre nóiméad déag tar éis a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 16)), "Tá sé sé nóiméad déag tar éis a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 17)), "Tá sé seacht nóiméad déag tar éis a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 18)), "Tá sé ocht nóiméad déag tar éis a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 19)), "Tá sé naoi nóiméad déag tar éis a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 21)), "Tá sé fiche a haon nóiméad tar éis a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 22)), "Tá sé fiche a dó nóiméad tar éis a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 23)), "Tá sé fiche a trí nóiméad tar éis a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 24)), "Tá sé fiche a ceathair nóiméad tar éis a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 25)), "Tá sé fiche a cúig nóiméad tar éis a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 26)), "Tá sé fiche a sé nóiméad tar éis a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 27)), "Tá sé fiche a seacht nóiméad tar éis a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 28)), "Tá sé fiche a hocht nóiméad tar éis a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 29)), "Tá sé fiche a naoi nóiméad tar éis a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 31)), "Tá sé fiche a naoi nóiméad chun a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 32)), "Tá sé fiche a hocht nóiméad chun a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 33)), "Tá sé fiche a seacht nóiméad chun a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 34)), "Tá sé fiche a sé nóiméad chun a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 35)), "Tá sé fiche a cúig nóiméad chun a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 36)), "Tá sé fiche a ceathair nóiméad chun a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 37)), "Tá sé fiche a trí nóiméad chun a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 38)), "Tá sé fiche a dó nóiméad chun a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 39)), "Tá sé fiche a haon nóiméad chun a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 41)), "Tá sé naoi nóiméad déag chun a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 42)), "Tá sé ocht nóiméad déag chun a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 43)), "Tá sé seacht nóiméad déag chun a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 44)), "Tá sé sé nóiméad déag chun a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 46)), "Tá sé ceithre nóiméad déag chun a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 47)), "Tá sé trí nóiméad déag chun a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 48)), "Tá sé dhá nóiméad déag chun a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 49)), "Tá sé aon nóiméad déag chun a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 12, minute: 59)), "Tá sé nóiméad amháin chun a haon")

        // --- 1:00 to 2:00 ---
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 1)), "Tá sé nóiméad amháin tar éis a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 11)), "Tá sé aon nóiméad déag tar éis a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 12)), "Tá sé dhá nóiméad déag tar éis a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 13)), "Tá sé trí nóiméad déag tar éis a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 14)), "Tá sé ceithre nóiméad déag tar éis a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 16)), "Tá sé sé nóiméad déag tar éis a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 17)), "Tá sé seacht nóiméad déag tar éis a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 18)), "Tá sé ocht nóiméad déag tar éis a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 19)), "Tá sé naoi nóiméad déag tar éis a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 21)), "Tá sé fiche a haon nóiméad tar éis a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 22)), "Tá sé fiche a dó nóiméad tar éis a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 23)), "Tá sé fiche a trí nóiméad tar éis a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 24)), "Tá sé fiche a ceathair nóiméad tar éis a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 25)), "Tá sé fiche a cúig nóiméad tar éis a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 26)), "Tá sé fiche a sé nóiméad tar éis a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 27)), "Tá sé fiche a seacht nóiméad tar éis a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 28)), "Tá sé fiche a hocht nóiméad tar éis a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 29)), "Tá sé fiche a naoi nóiméad tar éis a haon")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 31)), "Tá sé fiche a naoi nóiméad chun a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 32)), "Tá sé fiche a hocht nóiméad chun a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 33)), "Tá sé fiche a seacht nóiméad chun a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 34)), "Tá sé fiche a sé nóiméad chun a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 35)), "Tá sé fiche a cúig nóiméad chun a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 36)), "Tá sé fiche a ceathair nóiméad chun a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 37)), "Tá sé fiche a trí nóiméad chun a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 38)), "Tá sé fiche a dó nóiméad chun a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 39)), "Tá sé fiche a haon nóiméad chun a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 41)), "Tá sé naoi nóiméad déag chun a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 42)), "Tá sé ocht nóiméad déag chun a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 43)), "Tá sé seacht nóiméad déag chun a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 44)), "Tá sé sé nóiméad déag chun a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 46)), "Tá sé ceithre nóiméad déag chun a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 47)), "Tá sé trí nóiméad déag chun a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 48)), "Tá sé dhá nóiméad déag chun a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 49)), "Tá sé aon nóiméad déag chun a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 1, minute: 59)), "Tá sé nóiméad amháin chun a dó")

        // --- 2:00 to 3:00 ---
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 1)), "Tá sé nóiméad amháin tar éis a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 11)), "Tá sé aon nóiméad déag tar éis a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 12)), "Tá sé dhá nóiméad déag tar éis a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 13)), "Tá sé trí nóiméad déag tar éis a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 14)), "Tá sé ceithre nóiméad déag tar éis a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 16)), "Tá sé sé nóiméad déag tar éis a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 17)), "Tá sé seacht nóiméad déag tar éis a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 18)), "Tá sé ocht nóiméad déag tar éis a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 19)), "Tá sé naoi nóiméad déag tar éis a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 21)), "Tá sé fiche a haon nóiméad tar éis a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 22)), "Tá sé fiche a dó nóiméad tar éis a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 23)), "Tá sé fiche a trí nóiméad tar éis a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 24)), "Tá sé fiche a ceathair nóiméad tar éis a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 25)), "Tá sé fiche a cúig nóiméad tar éis a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 26)), "Tá sé fiche a sé nóiméad tar éis a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 27)), "Tá sé fiche a seacht nóiméad tar éis a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 28)), "Tá sé fiche a hocht nóiméad tar éis a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 29)), "Tá sé fiche a naoi nóiméad tar éis a dó")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 31)), "Tá sé fiche a naoi nóiméad chun a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 32)), "Tá sé fiche a hocht nóiméad chun a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 33)), "Tá sé fiche a seacht nóiméad chun a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 34)), "Tá sé fiche a sé nóiméad chun a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 35)), "Tá sé fiche a cúig nóiméad chun a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 36)), "Tá sé fiche a ceathair nóiméad chun a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 37)), "Tá sé fiche a trí nóiméad chun a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 38)), "Tá sé fiche a dó nóiméad chun a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 39)), "Tá sé fiche a haon nóiméad chun a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 41)), "Tá sé naoi nóiméad déag chun a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 42)), "Tá sé ocht nóiméad déag chun a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 43)), "Tá sé seacht nóiméad déag chun a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 44)), "Tá sé sé nóiméad déag chun a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 46)), "Tá sé ceithre nóiméad déag chun a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 47)), "Tá sé trí nóiméad déag chun a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 48)), "Tá sé dhá nóiméad déag chun a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 49)), "Tá sé aon nóiméad déag chun a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 2, minute: 59)), "Tá sé nóiméad amháin chun a trí")

        // --- 3:00 to 4:00 ---
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 1)), "Tá sé nóiméad amháin tar éis a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 11)), "Tá sé aon nóiméad déag tar éis a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 12)), "Tá sé dhá nóiméad déag tar éis a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 13)), "Tá sé trí nóiméad déag tar éis a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 14)), "Tá sé ceithre nóiméad déag tar éis a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 16)), "Tá sé sé nóiméad déag tar éis a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 17)), "Tá sé seacht nóiméad déag tar éis a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 18)), "Tá sé ocht nóiméad déag tar éis a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 19)), "Tá sé naoi nóiméad déag tar éis a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 21)), "Tá sé fiche a haon nóiméad tar éis a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 22)), "Tá sé fiche a dó nóiméad tar éis a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 23)), "Tá sé fiche a trí nóiméad tar éis a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 24)), "Tá sé fiche a ceathair nóiméad tar éis a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 25)), "Tá sé fiche a cúig nóiméad tar éis a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 26)), "Tá sé fiche a sé nóiméad tar éis a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 27)), "Tá sé fiche a seacht nóiméad tar éis a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 28)), "Tá sé fiche a hocht nóiméad tar éis a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 29)), "Tá sé fiche a naoi nóiméad tar éis a trí")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 31)), "Tá sé fiche a naoi nóiméad chun a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 32)), "Tá sé fiche a hocht nóiméad chun a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 33)), "Tá sé fiche a seacht nóiméad chun a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 34)), "Tá sé fiche a sé nóiméad chun a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 35)), "Tá sé fiche a cúig nóiméad chun a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 36)), "Tá sé fiche a ceathair nóiméad chun a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 37)), "Tá sé fiche a trí nóiméad chun a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 38)), "Tá sé fiche a dó nóiméad chun a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 39)), "Tá sé fiche a haon nóiméad chun a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 41)), "Tá sé naoi nóiméad déag chun a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 42)), "Tá sé ocht nóiméad déag chun a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 43)), "Tá sé seacht nóiméad déag chun a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 44)), "Tá sé sé nóiméad déag chun a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 46)), "Tá sé ceithre nóiméad déag chun a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 47)), "Tá sé trí nóiméad déag chun a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 48)), "Tá sé dhá nóiméad déag chun a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 49)), "Tá sé aon nóiméad déag chun a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 3, minute: 59)), "Tá sé nóiméad amháin chun a ceathair")

        // --- 4:00 to 5:00 ---
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 1)), "Tá sé nóiméad amháin tar éis a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 11)), "Tá sé aon nóiméad déag tar éis a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 12)), "Tá sé dhá nóiméad déag tar éis a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 13)), "Tá sé trí nóiméad déag tar éis a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 14)), "Tá sé ceithre nóiméad déag tar éis a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 16)), "Tá sé sé nóiméad déag tar éis a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 17)), "Tá sé seacht nóiméad déag tar éis a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 18)), "Tá sé ocht nóiméad déag tar éis a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 19)), "Tá sé naoi nóiméad déag tar éis a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 21)), "Tá sé fiche a haon nóiméad tar éis a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 22)), "Tá sé fiche a dó nóiméad tar éis a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 23)), "Tá sé fiche a trí nóiméad tar éis a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 24)), "Tá sé fiche a ceathair nóiméad tar éis a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 25)), "Tá sé fiche a cúig nóiméad tar éis a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 26)), "Tá sé fiche a sé nóiméad tar éis a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 27)), "Tá sé fiche a seacht nóiméad tar éis a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 28)), "Tá sé fiche a hocht nóiméad tar éis a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 29)), "Tá sé fiche a naoi nóiméad tar éis a ceathair")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 31)), "Tá sé fiche a naoi nóiméad chun a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 32)), "Tá sé fiche a hocht nóiméad chun a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 33)), "Tá sé fiche a seacht nóiméad chun a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 34)), "Tá sé fiche a sé nóiméad chun a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 35)), "Tá sé fiche a cúig nóiméad chun a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 36)), "Tá sé fiche a ceathair nóiméad chun a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 37)), "Tá sé fiche a trí nóiméad chun a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 38)), "Tá sé fiche a dó nóiméad chun a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 39)), "Tá sé fiche a haon nóiméad chun a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 41)), "Tá sé naoi nóiméad déag chun a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 42)), "Tá sé ocht nóiméad déag chun a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 43)), "Tá sé seacht nóiméad déag chun a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 44)), "Tá sé sé nóiméad déag chun a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 46)), "Tá sé ceithre nóiméad déag chun a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 47)), "Tá sé trí nóiméad déag chun a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 48)), "Tá sé dhá nóiméad déag chun a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 49)), "Tá sé aon nóiméad déag chun a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 4, minute: 59)), "Tá sé nóiméad amháin chun a cúig")

        // --- 5:00 to 6:00 ---
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 1)), "Tá sé nóiméad amháin tar éis a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 11)), "Tá sé aon nóiméad déag tar éis a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 12)), "Tá sé dhá nóiméad déag tar éis a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 13)), "Tá sé trí nóiméad déag tar éis a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 14)), "Tá sé ceithre nóiméad déag tar éis a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 16)), "Tá sé sé nóiméad déag tar éis a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 17)), "Tá sé seacht nóiméad déag tar éis a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 18)), "Tá sé ocht nóiméad déag tar éis a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 19)), "Tá sé naoi nóiméad déag tar éis a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 21)), "Tá sé fiche a haon nóiméad tar éis a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 22)), "Tá sé fiche a dó nóiméad tar éis a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 23)), "Tá sé fiche a trí nóiméad tar éis a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 24)), "Tá sé fiche a ceathair nóiméad tar éis a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 25)), "Tá sé fiche a cúig nóiméad tar éis a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 26)), "Tá sé fiche a sé nóiméad tar éis a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 27)), "Tá sé fiche a seacht nóiméad tar éis a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 28)), "Tá sé fiche a hocht nóiméad tar éis a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 29)), "Tá sé fiche a naoi nóiméad tar éis a cúig")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 31)), "Tá sé fiche a naoi nóiméad chun a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 32)), "Tá sé fiche a hocht nóiméad chun a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 33)), "Tá sé fiche a seacht nóiméad chun a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 34)), "Tá sé fiche a sé nóiméad chun a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 35)), "Tá sé fiche a cúig nóiméad chun a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 36)), "Tá sé fiche a ceathair nóiméad chun a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 37)), "Tá sé fiche a trí nóiméad chun a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 38)), "Tá sé fiche a dó nóiméad chun a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 39)), "Tá sé fiche a haon nóiméad chun a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 41)), "Tá sé naoi nóiméad déag chun a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 42)), "Tá sé ocht nóiméad déag chun a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 43)), "Tá sé seacht nóiméad déag chun a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 44)), "Tá sé sé nóiméad déag chun a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 46)), "Tá sé ceithre nóiméad déag chun a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 47)), "Tá sé trí nóiméad déag chun a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 48)), "Tá sé dhá nóiméad déag chun a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 49)), "Tá sé aon nóiméad déag chun a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 5, minute: 59)), "Tá sé nóiméad amháin chun a sé")

        // --- 6:00 to 7:00 ---
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 1)), "Tá sé nóiméad amháin tar éis a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 11)), "Tá sé aon nóiméad déag tar éis a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 12)), "Tá sé dhá nóiméad déag tar éis a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 13)), "Tá sé trí nóiméad déag tar éis a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 14)), "Tá sé ceithre nóiméad déag tar éis a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 16)), "Tá sé sé nóiméad déag tar éis a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 17)), "Tá sé seacht nóiméad déag tar éis a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 18)), "Tá sé ocht nóiméad déag tar éis a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 19)), "Tá sé naoi nóiméad déag tar éis a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 21)), "Tá sé fiche a haon nóiméad tar éis a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 22)), "Tá sé fiche a dó nóiméad tar éis a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 23)), "Tá sé fiche a trí nóiméad tar éis a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 24)), "Tá sé fiche a ceathair nóiméad tar éis a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 25)), "Tá sé fiche a cúig nóiméad tar éis a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 26)), "Tá sé fiche a sé nóiméad tar éis a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 27)), "Tá sé fiche a seacht nóiméad tar éis a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 28)), "Tá sé fiche a hocht nóiméad tar éis a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 29)), "Tá sé fiche a naoi nóiméad tar éis a sé")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 31)), "Tá sé fiche a naoi nóiméad chun a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 32)), "Tá sé fiche a hocht nóiméad chun a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 33)), "Tá sé fiche a seacht nóiméad chun a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 34)), "Tá sé fiche a sé nóiméad chun a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 35)), "Tá sé fiche a cúig nóiméad chun a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 36)), "Tá sé fiche a ceathair nóiméad chun a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 37)), "Tá sé fiche a trí nóiméad chun a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 38)), "Tá sé fiche a dó nóiméad chun a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 39)), "Tá sé fiche a haon nóiméad chun a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 41)), "Tá sé naoi nóiméad déag chun a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 42)), "Tá sé ocht nóiméad déag chun a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 43)), "Tá sé seacht nóiméad déag chun a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 44)), "Tá sé sé nóiméad déag chun a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 46)), "Tá sé ceithre nóiméad déag chun a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 47)), "Tá sé trí nóiméad déag chun a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 48)), "Tá sé dhá nóiméad déag chun a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 49)), "Tá sé aon nóiméad déag chun a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 6, minute: 59)), "Tá sé nóiméad amháin chun a seacht")

        // --- 7:00 to 8:00 ---
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 1)), "Tá sé nóiméad amháin tar éis a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 11)), "Tá sé aon nóiméad déag tar éis a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 12)), "Tá sé dhá nóiméad déag tar éis a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 13)), "Tá sé trí nóiméad déag tar éis a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 14)), "Tá sé ceithre nóiméad déag tar éis a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 16)), "Tá sé sé nóiméad déag tar éis a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 17)), "Tá sé seacht nóiméad déag tar éis a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 18)), "Tá sé ocht nóiméad déag tar éis a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 19)), "Tá sé naoi nóiméad déag tar éis a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 21)), "Tá sé fiche a haon nóiméad tar éis a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 22)), "Tá sé fiche a dó nóiméad tar éis a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 23)), "Tá sé fiche a trí nóiméad tar éis a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 24)), "Tá sé fiche a ceathair nóiméad tar éis a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 25)), "Tá sé fiche a cúig nóiméad tar éis a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 26)), "Tá sé fiche a sé nóiméad tar éis a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 27)), "Tá sé fiche a seacht nóiméad tar éis a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 28)), "Tá sé fiche a hocht nóiméad tar éis a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 29)), "Tá sé fiche a naoi nóiméad tar éis a seacht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 31)), "Tá sé fiche a naoi nóiméad chun a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 32)), "Tá sé fiche a hocht nóiméad chun a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 33)), "Tá sé fiche a seacht nóiméad chun a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 34)), "Tá sé fiche a sé nóiméad chun a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 35)), "Tá sé fiche a cúig nóiméad chun a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 36)), "Tá sé fiche a ceathair nóiméad chun a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 37)), "Tá sé fiche a trí nóiméad chun a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 38)), "Tá sé fiche a dó nóiméad chun a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 39)), "Tá sé fiche a haon nóiméad chun a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 41)), "Tá sé naoi nóiméad déag chun a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 42)), "Tá sé ocht nóiméad déag chun a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 43)), "Tá sé seacht nóiméad déag chun a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 44)), "Tá sé sé nóiméad déag chun a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 46)), "Tá sé ceithre nóiméad déag chun a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 47)), "Tá sé trí nóiméad déag chun a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 48)), "Tá sé dhá nóiméad déag chun a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 49)), "Tá sé aon nóiméad déag chun a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 7, minute: 59)), "Tá sé nóiméad amháin chun a hocht")

        // --- 8:00 to 9:00 ---
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 1)), "Tá sé nóiméad amháin tar éis a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 11)), "Tá sé aon nóiméad déag tar éis a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 12)), "Tá sé dhá nóiméad déag tar éis a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 13)), "Tá sé trí nóiméad déag tar éis a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 14)), "Tá sé ceithre nóiméad déag tar éis a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 16)), "Tá sé sé nóiméad déag tar éis a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 17)), "Tá sé seacht nóiméad déag tar éis a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 18)), "Tá sé ocht nóiméad déag tar éis a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 19)), "Tá sé naoi nóiméad déag tar éis a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 21)), "Tá sé fiche a haon nóiméad tar éis a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 22)), "Tá sé fiche a dó nóiméad tar éis a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 23)), "Tá sé fiche a trí nóiméad tar éis a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 24)), "Tá sé fiche a ceathair nóiméad tar éis a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 25)), "Tá sé fiche a cúig nóiméad tar éis a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 26)), "Tá sé fiche a sé nóiméad tar éis a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 27)), "Tá sé fiche a seacht nóiméad tar éis a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 28)), "Tá sé fiche a hocht nóiméad tar éis a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 29)), "Tá sé fiche a naoi nóiméad tar éis a hocht")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 31)), "Tá sé fiche a naoi nóiméad chun a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 32)), "Tá sé fiche a hocht nóiméad chun a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 33)), "Tá sé fiche a seacht nóiméad chun a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 34)), "Tá sé fiche a sé nóiméad chun a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 35)), "Tá sé fiche a cúig nóiméad chun a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 36)), "Tá sé fiche a ceathair nóiméad chun a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 37)), "Tá sé fiche a trí nóiméad chun a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 38)), "Tá sé fiche a dó nóiméad chun a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 39)), "Tá sé fiche a haon nóiméad chun a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 41)), "Tá sé naoi nóiméad déag chun a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 42)), "Tá sé ocht nóiméad déag chun a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 43)), "Tá sé seacht nóiméad déag chun a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 44)), "Tá sé sé nóiméad déag chun a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 46)), "Tá sé ceithre nóiméad déag chun a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 47)), "Tá sé trí nóiméad déag chun a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 48)), "Tá sé dhá nóiméad déag chun a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 49)), "Tá sé aon nóiméad déag chun a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 8, minute: 59)), "Tá sé nóiméad amháin chun a naoi")

        // --- 9:00 to 10:00 ---
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 1)), "Tá sé nóiméad amháin tar éis a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 11)), "Tá sé aon nóiméad déag tar éis a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 12)), "Tá sé dhá nóiméad déag tar éis a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 13)), "Tá sé trí nóiméad déag tar éis a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 14)), "Tá sé ceithre nóiméad déag tar éis a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 16)), "Tá sé sé nóiméad déag tar éis a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 17)), "Tá sé seacht nóiméad déag tar éis a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 18)), "Tá sé ocht nóiméad déag tar éis a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 19)), "Tá sé naoi nóiméad déag tar éis a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 21)), "Tá sé fiche a haon nóiméad tar éis a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 22)), "Tá sé fiche a dó nóiméad tar éis a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 23)), "Tá sé fiche a trí nóiméad tar éis a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 24)), "Tá sé fiche a ceathair nóiméad tar éis a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 25)), "Tá sé fiche a cúig nóiméad tar éis a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 26)), "Tá sé fiche a sé nóiméad tar éis a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 27)), "Tá sé fiche a seacht nóiméad tar éis a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 28)), "Tá sé fiche a hocht nóiméad tar éis a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 29)), "Tá sé fiche a naoi nóiméad tar éis a naoi")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 31)), "Tá sé fiche a naoi nóiméad chun a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 32)), "Tá sé fiche a hocht nóiméad chun a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 33)), "Tá sé fiche a seacht nóiméad chun a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 34)), "Tá sé fiche a sé nóiméad chun a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 35)), "Tá sé fiche a cúig nóiméad chun a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 36)), "Tá sé fiche a ceathair nóiméad chun a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 37)), "Tá sé fiche a trí nóiméad chun a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 38)), "Tá sé fiche a dó nóiméad chun a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 39)), "Tá sé fiche a haon nóiméad chun a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 41)), "Tá sé naoi nóiméad déag chun a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 42)), "Tá sé ocht nóiméad déag chun a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 43)), "Tá sé seacht nóiméad déag chun a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 44)), "Tá sé sé nóiméad déag chun a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 46)), "Tá sé ceithre nóiméad déag chun a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 47)), "Tá sé trí nóiméad déag chun a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 48)), "Tá sé dhá nóiméad déag chun a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 49)), "Tá sé aon nóiméad déag chun a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 9, minute: 59)), "Tá sé nóiméad amháin chun a deich")

        // --- 10:00 to 11:00 ---
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 1)), "Tá sé nóiméad amháin tar éis a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 11)), "Tá sé aon nóiméad déag tar éis a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 12)), "Tá sé dhá nóiméad déag tar éis a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 13)), "Tá sé trí nóiméad déag tar éis a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 14)), "Tá sé ceithre nóiméad déag tar éis a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 16)), "Tá sé sé nóiméad déag tar éis a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 17)), "Tá sé seacht nóiméad déag tar éis a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 18)), "Tá sé ocht nóiméad déag tar éis a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 19)), "Tá sé naoi nóiméad déag tar éis a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 21)), "Tá sé fiche a haon nóiméad tar éis a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 22)), "Tá sé fiche a dó nóiméad tar éis a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 23)), "Tá sé fiche a trí nóiméad tar éis a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 24)), "Tá sé fiche a ceathair nóiméad tar éis a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 25)), "Tá sé fiche a cúig nóiméad tar éis a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 26)), "Tá sé fiche a sé nóiméad tar éis a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 27)), "Tá sé fiche a seacht nóiméad tar éis a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 28)), "Tá sé fiche a hocht nóiméad tar éis a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 29)), "Tá sé fiche a naoi nóiméad tar éis a deich")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 31)), "Tá sé fiche a naoi nóiméad chun a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 32)), "Tá sé fiche a hocht nóiméad chun a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 33)), "Tá sé fiche a seacht nóiméad chun a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 34)), "Tá sé fiche a sé nóiméad chun a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 35)), "Tá sé fiche a cúig nóiméad chun a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 36)), "Tá sé fiche a ceathair nóiméad chun a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 37)), "Tá sé fiche a trí nóiméad chun a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 38)), "Tá sé fiche a dó nóiméad chun a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 39)), "Tá sé fiche a haon nóiméad chun a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 41)), "Tá sé naoi nóiméad déag chun a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 42)), "Tá sé ocht nóiméad déag chun a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 43)), "Tá sé seacht nóiméad déag chun a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 44)), "Tá sé sé nóiméad déag chun a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 46)), "Tá sé ceithre nóiméad déag chun a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 47)), "Tá sé trí nóiméad déag chun a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 48)), "Tá sé dhá nóiméad déag chun a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 49)), "Tá sé aon nóiméad déag chun a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 10, minute: 59)), "Tá sé nóiméad amháin chun a haon déag")

        // --- 11:00 to 12:00 ---
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 1)), "Tá sé nóiméad amháin tar éis a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 11)), "Tá sé aon nóiméad déag tar éis a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 12)), "Tá sé dhá nóiméad déag tar éis a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 13)), "Tá sé trí nóiméad déag tar éis a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 14)), "Tá sé ceithre nóiméad déag tar éis a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 16)), "Tá sé sé nóiméad déag tar éis a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 17)), "Tá sé seacht nóiméad déag tar éis a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 18)), "Tá sé ocht nóiméad déag tar éis a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 19)), "Tá sé naoi nóiméad déag tar éis a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 21)), "Tá sé fiche a haon nóiméad tar éis a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 22)), "Tá sé fiche a dó nóiméad tar éis a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 23)), "Tá sé fiche a trí nóiméad tar éis a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 24)), "Tá sé fiche a ceathair nóiméad tar éis a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 25)), "Tá sé fiche a cúig nóiméad tar éis a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 26)), "Tá sé fiche a sé nóiméad tar éis a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 27)), "Tá sé fiche a seacht nóiméad tar éis a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 28)), "Tá sé fiche a hocht nóiméad tar éis a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 29)), "Tá sé fiche a naoi nóiméad tar éis a haon déag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 31)), "Tá sé fiche a naoi nóiméad chun a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 32)), "Tá sé fiche a hocht nóiméad chun a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 33)), "Tá sé fiche a seacht nóiméad chun a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 34)), "Tá sé fiche a sé nóiméad chun a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 35)), "Tá sé fiche a cúig nóiméad chun a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 36)), "Tá sé fiche a ceathair nóiméad chun a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 37)), "Tá sé fiche a trí nóiméad chun a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 38)), "Tá sé fiche a dó nóiméad chun a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 39)), "Tá sé fiche a haon nóiméad chun a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 41)), "Tá sé naoi nóiméad déag chun a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 42)), "Tá sé ocht nóiméad déag chun a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 43)), "Tá sé seacht nóiméad déag chun a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 44)), "Tá sé sé nóiméad déag chun a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 46)), "Tá sé ceithre nóiméad déag chun a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 47)), "Tá sé trí nóiméad déag chun a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 48)), "Tá sé dhá nóiméad déag chun a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 49)), "Tá sé aon nóiméad déag chun a dó dhéag")
        XCTAssertEqual(GaeilgeTimeFormatter.getIrishTimePhrase(date: createDate(hour: 11, minute: 59)), "Tá sé nóiméad amháin chun a dó dhéag")
    }
}